charts/karavi-metrics-powerflex/README.md
charts/karavi-metrics-powerflex/VERSIONING_WORKFLOW.md
charts/karavi-observability/README.md
charts/karavi-observability/VERSIONING_WORKFLOW.md
charts/karavi-topology/README.md
charts/karavi-topology/VERSIONING_WORKFLOW.md

No
Updated helm repo add command
- #39

Updated helm repo add command

---

charts/karavi-metrics-powerflex/Chart.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-topology/Chart.yaml

No
Updated app version in helm charts
- #39

Updated app version in helm charts

---

README.md
charts/karavi-observability/README.md

No
Added documentation for PowerFlex administrator password
- #39

Added documentation for PowerFlex administrator password

---

charts/karavi-metrics-powerflex/Chart.yaml
charts/karavi-metrics-powerflex/nginx.conf
charts/karavi-metrics-powerflex/templates/NOTES.txt
charts/karavi-metrics-powerflex/templates/otel-collector.yaml
charts/karavi-metrics-powerflex/values.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-topology/Chart.yaml
charts/karavi-topology/templates/karavi-topology.yaml
charts/karavi-topology/values.yaml

No.
- #61 
[e2e_test_ocp_4.5.log](https://github.com/dell/helm-charts/files/5662732/e2e_test_ocp_4.5.log)
[e2e_test_ocp_4.6.log](https://github.com/dell/helm-charts/files/5662734/e2e_test_ocp_4.6.log)

[charts/karavi-metrics-powerflex] [charts/karavi-topology] Fix nginx configuration to work for Openshift deployment

---

charts/karavi-observability/README.md

No
Updates the link to the Getting Started guide in Karavi Observability
https://github.com/dell/karavi-observability/issues/1

Updated URL to Karavi Observability getting started guide

---

charts/karavi-observability/templates/otel-collector.yaml

No
The previous version put config files as quoted-string which makes it difficult to modify in Kubernetes manually since indentation is part of the language.
- #70

[charts/karavi-metrics-powerflex] Use yaml multiline for ConfigMap files

---

.github/workflows/charts-release-action.yml
.github/workflows/helm-validations.yml

No
The PR filter for Github actions is not working due to a syntax error. The filter has been updated to run only on PR merges to the main branch.
- #79 

Bugfix GitHub actions

---

charts/karavi-observability/templates/NOTES.txt
charts/karavi-observability/templates/karavi-metrics-powerflex-service-account.yaml
charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
charts/karavi-observability/templates/karavi-metrics-powerstore-service-account.yaml
charts/karavi-observability/templates/karavi-metrics-powerstore.yaml
charts/karavi-observability/templates/karavi-observability-configmap.yaml
charts/karavi-observability/templates/karavi-topology-service-account.yaml
charts/karavi-observability/templates/karavi-topology.yaml
charts/karavi-observability/values.yaml

No
Updates the helm chart for Observability to support PowerStore metrics.
- https://github.com/dell/karavi-observability/issues/48

Updated helm chart to support PowerStore metrics

---

.github/workflows/helm-validations.yml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/otel-collector-config.yaml
charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
charts/karavi-observability/templates/karavi-metrics-powerstore.yaml
charts/karavi-observability/templates/karavi-topology.yaml
charts/karavi-observability/values.yaml

No
Updating the Observability chart to point to the newly released v1.1.0 images.
N/A

[charts/karavi-observability] Observability release v1.1.0

---

charts/csm-authorization/templates/NOTES.txt
charts/csm-authorization/templates/certificate.yaml
charts/csm-authorization/templates/ingress.yaml
charts/csm-authorization/templates/karavi-storage-secret.yaml
charts/csm-authorization/templates/storage-service.yaml
charts/csm-authorization/values.yaml

No
The PR adds a new template for storage-service deployment.
- #109 

KRV-4943-storage-service

---

charts/csm-authorization/policies/powermax-url.rego
charts/csm-authorization/policies/powerscale-url.rego
charts/csm-authorization/policies/url-test.rego
charts/csm-authorization/policies/url.rego
charts/csm-authorization/policies/volumes-create-test.rego
charts/csm-authorization/policies/volumes-create.rego
charts/csm-authorization/policies/volumes-delete.rego
charts/csm-authorization/policies/volumes-map.rego
charts/csm-authorization/policies/volumes-powermax-create.rego
charts/csm-authorization/policies/volumes-powerscale-create.rego
charts/csm-authorization/policies/volumes-unmap.rego
charts/csm-authorization/templates/certificate.yaml
charts/csm-authorization/templates/proxy-server.yaml
charts/csm-authorization/values.yaml

No
- Configures the self-signed certificate with the hosts specified in the values file so TLS termination works
- Fixes OPA service account and other OPA configurations for policies to be registered
- Updates copyright and comments
- https://github.com/dell/csm/issues/261

[feature-261]: Fix opa policies and self-signed certificate host names

---

charts/karavi-observability/otel-collector-config.yaml

Fixed TLS Settings for patch

---

charts/karavi-observability/Chart.yaml
charts/karavi-observability/otel-collector-config.yaml

Yes
- #[288](https://github.com/dell/csm/issues/288)

[karavi-observability] Patch release 1.1.1

---

charts/karavi-observability/Chart.yaml
charts/karavi-observability/otel-collector-config.yaml

Yes
- #[CSM 288](https://github.com/dell/csm/issues/288)

[karavi-observability] release

---

charts/karavi-observability/values.yaml

[charts/karavi-observability] Updates for release v1.2.0 

---

.github/CODEOWNERS

No
Correct CODEOWNERS format
n/a

Correct codeowners format

---

charts/csm-authorization/values.yaml

No
Update Authorization images to latest 1.4.0 image
| https://github.com/dell/csm/issues/350 |

Update Authorization images to v1.4.0

---

charts/karavi-observability/values.yaml

No
- #https://github.com/dell/csm/issues/350

charts/karavi-observability Update observability image tags for CSM 1.4 release

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/policies/url.rego
charts/csm-authorization/templates/policies.yaml
charts/csm-authorization/templates/proxy-server.yaml
charts/csm-authorization/values.yaml

No
- [#350](https://github.com/dell/csm/issues/350)

charts/csm-authorization: Release v1.4.0

---

charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml

Update csm-metrics-powerscale to 1.0.0 to accommodate csm-metrics-powerscale release
No
- #https://github.com/dell/csm/issues/350

charts/karavi-observability: Update csm-metrics-powerscale to 1.0.0

---

charts/karavi-observability/Chart.yaml
charts/karavi-observability/README.md

Upgrade cert-manager to 1.10.0
No
- #https://github.com/dell/csm/issues/491

charts/karavi-observability: upgrade certmanager

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml

Yes
Updates Authorization chart version and images for the CSM 1.5 release.
- https://github.com/dell/csm/issues/491

[charts/csm-authorization]: Update Authorization for 1.5 release

---

charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/values.yaml

No
Update chart and image versions
- https://github.com/dell/csm/issues/491

[charts/csm-application-mobility]: Update chart and image versions

---

charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/templates/apiextensions.k8s.io_v1_customresourcedefinition_schedules.mobility.storage.dell.com.yaml
charts/csm-application-mobility/templates/rbac.authorization.k8s.io_v1_clusterrole_app-mobility-manager-role.yaml
charts/csm-application-mobility/values.yaml

No
Updates helm chart for Application Mobility

[charts/csm-application-mobility]: Application Mobility v0.2.0 Release

---

charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/templates/apiextensions.k8s.io_v1_customresourcedefinition_schedules.mobility.storage.dell.com.yaml
charts/csm-application-mobility/templates/rbac.authorization.k8s.io_v1_clusterrole_app-mobility-manager-role.yaml
charts/csm-application-mobility/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/policies/url.rego
charts/csm-authorization/templates/policies.yaml
charts/csm-authorization/templates/proxy-server.yaml
charts/csm-authorization/values.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml

Rebase main

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml

[csm-authorization]: Update versions to 1.5

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml

[csm-authorization]: v1.5.0 release

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/charts-release-action.yml
.github/workflows/helm-validations.yml

No
- Updates mailing list email
- Updates actions/checkout due to node.js 12 actions being deprecated
- N/A

Update mailing list

---

charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml

No
- #[586](https://github.com/dell/csm/issues/586)

add support for pmax topology

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/karavi-observability/values.yaml

No
Change version from 1.5.0 to 1.5.1
- 408

[charts/csm-authorization] [feature-408] Change version to 1.5.1

---

charts/csm-authorization/templates/proxy-server.yaml

Yes/No
Updating Services on Proxy-server chart, needed for CSM 1.5.1 patch. 
- https://github.com/dell/csm/issues/582

Updating Services on Proxy-server chart

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/templates/csm-config-params.yaml
charts/csm-authorization/templates/proxy-server.yaml
charts/csm-authorization/values.yaml

Release 1.5.1

---

charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/values.yaml

No
- Updates version numbers for Application Mobility chart
- https://github.com/dell/csm/issues/583

[charts/csm-application-mobility]: Update Application Mobility chart with new image and chart versions

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/templates/_helpers.tpl
charts/csm-replication/templates/controller.yaml

No
This PR is to update the latest changes in the charts.
https://github.com/dell/csm/issues/591

Updated Powerstore, PowerMax and Replication charts with latest changes

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml

No
To update version changes in CSM charts for Application-Mobility
https://github.com/dell/csm/issues/591

updated chart version for app-mobility in CSM charts

---

charts/csi-powerstore/values.yaml

No
To update code changes in Powerstore helm charts
https://github.com/dell/csm/issues/591

Updated Powerstore helm charts

---

charts/csm-encryption-rekey-controller/Chart.yaml
charts/csm-encryption-rekey-controller/values.yaml

No
- Updates version numbers for Encryption chart
- https://github.com/dell/csm/issues/583

[charts/csm-encryption-rekey-controller] Image and chart version bumped up.

---

charts/karavi-observability/README.md
charts/karavi-observability/values.yaml

No
- Updates version numbers for Observability modules.
- https://github.com/dell/csm/issues/583

[charts/karavi-observability] Bump up images for Observability

---

charts/csi-powermax/templates/_helpers.tpl

Yes/No
- https://github.com/dell/csm/issues/744

Change K8s registry to registry.k8s.io

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/values.yaml
charts/csi-vxflexos/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml

No
Updated replication-controller image to v1.5.0, init, replicator/migrator/rescanner side car versions.

[charts/csm-replication]: Updated image versions

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/templates/_helpers.tpl
charts/csi-isilon/templates/controller.yaml
charts/csi-isilon/templates/csidriver.yaml
charts/csi-isilon/values.yaml

No
It is to support CSI-Powerscale 2.7.0 driver

[charts/csi-isilon]Added Powerscale 2.7.0 Support

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/Chart.yaml
charts/csi-powermax/values.yaml

No
1. Updating Chart version number
2. Updating driver/reverseproxy versions

update chart version for powermax

---

charts/container-storage-modules/values.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/values.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization/values.yaml
charts/karavi-observability/values.yaml

update to 1.7

---

charts/csi-vxflexos/templates/_helpers.tpl
charts/csi-vxflexos/values.yaml

No
side car versions updated for csi-powerflex driver
https://github.com/dell/csm/issues/743 

sidecar versions updated for powerflex driver

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/templates/_helpers.tpl
charts/container-storage-modules/values.yaml

No
- #Issue_Number](https://github.com/dell/csm/issues/743

reverting 

---

charts/csm-authorization/Chart.yaml
charts/csm-replication/Chart.yaml

No
- #https://github.com/dell/csm/issues/743

authorization charts

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/templates/_helpers.tpl
charts/container-storage-modules/values.yaml

No
- #https://github.com/dell/csm/issues/743

add CSM charts for 1.7.0

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/templates/_helpers.tpl
charts/container-storage-modules/values.yaml
charts/karavi-observability/Chart.yaml

revert csm charts

---

charts/csm-replication/Chart.yaml

re-push replication release

---

charts/csi-isilon/Chart.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-unity/Chart.yaml
charts/csi-vxflexos/Chart.yaml
charts/csm-authorization/Chart.yaml

re-releasing tags

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/templates/_helpers.tpl
charts/container-storage-modules/values.yaml

add csm charts repos

---

charts/csi-powermax/templates/_helpers.tpl

Updated registry changes  for PowerMax

Updated registry changes 

---

.github/workflows/helm-validations.yml

No
To enable checks for all release branches

Updated helm-validations file to enable checks for all release branches

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/values.yaml

Yes
Powerscale v2.8.0 Release
- #[885](https://github.com/dell/csm/issues/885)

Powerscale v2.8.0 release

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml

No
To support CSM 1.7.1
- https://github.com/dell/csm/issues/911

add helm chart changes in CSM for v1.7.1 release.

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/templates/_helpers.tpl
charts/csi-unity/templates/controller.yaml
charts/csi-unity/templates/csidriver.yaml
charts/csi-unity/values.yaml

No
Updating the csi unity driver version to the latest version 2.8.0

CSIUnity v2.8.0 release 

---

.github/CODEOWNERS
charts/container-storage-modules/values.yaml
charts/csi-powermax/templates/node.yaml
charts/csi-powermax/values.yaml

Yes/No
This feature helps in limiting the number of Volume per node by the user.
https://github.com/dell/csm/issues/878
https://github.com/dell/csm/issues/878

Volume limits p max

---

.github/workflows/charts-release-action.yml

No
Configures the helm-chart-releaser action to skip existing releases. This is necessary when doing a patch release for a module, for example, where other modules aren't updated.
https://github.com/dell/helm-charts/actions/runs/5360664845/job/14514664745
https://github.com/dell/csm/issues/885

[feature-885]: Skip existing releases during chat releaser action

---

charts/container-storage-modules/values.yaml
charts/csi-powerstore/values.yaml

No
Updated csi-metadata-retriever version to 1.5.0 for CSI PowerStore
- https://github.com/dell/csm/issues/885

Updated csi-metadata-retriever version to 1.5.0 for CSI PowerStore

---

charts/container-storage-modules/Chart.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml

No
Update charts with new images versions for Observability.
- #[885](https://github.com/dell/csm/issues/885)

[karavi-observability] Update Observability image versions for CSM 1.8.

---

charts/container-storage-modules/values.yaml

No
Updated values for container-storage-modules for new keys for PowerFlex driver.
- https://github.com/dell/csm/issues/885 

[charts/container-storage-modules]: new keys added for PowerFlex driver

---

charts/container-storage-modules/values.yaml
charts/csi-vxflexos/templates/controller.yaml
charts/csi-vxflexos/values.yaml

[charts/csi-vxflexos]: NFS ACL parameter removed

---

charts/container-storage-modules/values.yaml

Yes/No
Added new fields for Powermax in CSM values file 
- https://github.com/dell/csm/issues/885 

Adding new fields for powermax

---

charts/cosi/values.yaml

No
Issue not open but the chart is broken nonetheless

[charts/cosi] Point to correct cosi image

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/templates/_helpers.tpl
charts/csi-vxflexos/values.yaml

[charts/csi-powerflex] Add PowerFlex v2.9.0 support & sidecar version update

---

.github/CODEOWNERS
charts/container-storage-modules/Chart.yaml
charts/csi-isilon/templates/controller.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml

No
This PR bumps up the csm observability versions for CSM 1.9

Bump up observability version for CSM 1.9

---

charts/container-storage-modules/values.yaml
charts/csi-powerstore/templates/_helpers.tpl
charts/csi-vxflexos/templates/_helpers.tpl
charts/csi-vxflexos/values.yaml

Update attacher and sdc sidecar for csi-powerflex and csi-powerstore

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml

[charts/csi-unity]: Update Unity version for CSM 1.9

---

charts/csi-unity/values.yaml

No
- [Issue-1012](https://github.com/dell/csm/issues/1012)

[charts/csi-unity] Update unity sidecar image versions

---

charts/container-storage-modules/values.yaml
charts/csi-vxflexos/values.yaml

SDC version changed from 4.5 to 3.6.1 for Powerflex

---

charts/container-storage-modules/values.yaml
charts/csi-powerstore/values.yaml
charts/csi-vxflexos/values.yaml

No
Updating the csi-sidecar versions in PowerStore and PowerFlex driver's sample file.

Sidecars version update for powerstore and powerflex

---

charts/container-storage-modules/values.yaml
charts/csi-vxflexos/values.yaml

Revert "SDC version changed from 4.5 to 3.6.1 for Powerflex"

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/values.yaml

No
Powerscale version bump up and latest side car version used 

Powerscale and sidecar version changes

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/values.yaml
charts/csi-powermax/values.yaml

PowerMax 2.9.0 support

---

charts/csi-powermax/values.yaml

Updating latest sidecars for PowerMax

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml

Release csm 1.9.0

---

charts/csm-authorization/Chart.yaml
charts/csm-authorization/crds/csm-authorization.storage.dell.com_csmroles.yaml
charts/csm-authorization/crds/csm-authorization.storage.dell.com_storages.yaml
charts/csm-authorization/templates/proxy-server.yaml
charts/csm-authorization/templates/storage-service.yaml
charts/csm-authorization/values.yaml

No
Adds Vault configurations, authentication and certificates, to storage service.

[csm-authorization]: Add Vault configuration to storage-service

---

charts/csm-authorization/templates/proxy-server.yaml

No
Updates proxy server service account namespace

[charts/csm-authorization]: Update service account namespace

---

charts/csm-authorization/templates/proxy-server.yaml
charts/csm-authorization/templates/role-service.yaml

No
Update role-service for re-architecture

Update role-service for gitops

---

charts/csi-isilon/Chart.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-unity/Chart.yaml
charts/csi-vxflexos/Chart.yaml

No
Support for K8S 1.29
- https://github.com/dell/csm/issues/1088

Updating helm charts to support k8s 1.29.0

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/templates/controller.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/values.yaml
charts/csi-powermax/templates/controller.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/templates/controller.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/templates/controller.yaml
charts/csi-vxflexos/templates/node.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml

Yes
- https://github.com/dell/csm/issues/1106
- https://github.com/dell/csm/issues/1099
- https://github.com/dell/csm/issues/1086
- https://github.com/dell/csm/issues/1110

Disable leader election in Helm charts

---

charts/csi-isilon/templates/controller.yaml
charts/csi-powermax/templates/controller.yaml
charts/csi-unity/templates/controller.yaml
charts/csi-vxflexos/templates/controller.yaml

No
https://github.com/dell/csm/issues/1110

Disabling leader election for driver container of controller pod

---

charts/csi-vxflexos/templates/node.yaml

No
Reverts changes from this PR https://github.com/dell/helm-charts/pull/347

Revert "Added env for kube node name" 

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml

Yes/No
- #[1109](https://github.com/dell/csm/issues/1109)

Removing csm changes from 1.9.1 

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml
charts/cosi/Chart.yaml
charts/cosi/values.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/templates/controller.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/values.yaml
charts/csi-powermax/templates/controller.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/templates/controller.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/templates/controller.yaml
charts/csi-vxflexos/templates/node.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml

No
- #[1109](https://github.com/dell/csm/issues/1109)

Release v1.9.1

---

.github/workflows/charts-release-action.yml

Yes/No
Updates helm-releaser to v1.6.0.
https://github.com/dell/csm/issues/1109

Update to latest helm releaser action

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml

Yes/No
Update CSM chart for v2.9.1.
https://github.com/dell/csm/issues/1109

Update CSM Chart for v2.9.1

---

charts/csi-vxflexos/templates/node.yaml

No
https://github.com/dell/csm/issues/1152

Mapping /opt/emc inside SDC container

---

charts/container-storage-modules/Chart.yaml

No
This PR updates the helm charts version
https://github.com/dell/csm/issues/1152

Helm Chart Version Bump

---

charts/container-storage-modules/Chart.yaml

No
Updating versions in container-storage-modules.yaml for release
https://github.com/dell/csm/issues/1164

helm-charts/charts/container-storage-modules/Chart.yaml updated with new versions

---

charts/container-storage-modules/values.yaml
charts/csi-isilon/values.yaml
charts/csi-powerstore/values.yaml
charts/csi-vxflexos/values.yaml

No
This PR bumps up the csi-volumegroup-snapshotter and csi-metadata-retriever CSM sidecars version
https://github.com/dell/csm/issues/1091

CSM Sidecars Version Bump

---

.github/workflows/charts-release-action.yml
charts/container-storage-modules/Chart.yaml
charts/cosi/Chart.yaml
charts/csi-vxflexos/templates/node.yaml
charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/values.yaml

Conflict fix verified (#388)

---

charts/container-storage-modules/Chart.yaml
charts/container-storage-modules/values.yaml

Adding CSM files ( Release Activity )
Yes/No

Adding CSM files ( Release Activity )

---

charts/csm-authorization/templates/proxy-server.yaml

Add watch event permissions for proxy-server

---

charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/templates/node.yaml
charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/values.yaml
installation-wizard/container-storage-modules/Chart.yaml

Fix Helm deployment of vxflexos driver

---

charts/csm-authorization/templates/proxy-server.yaml

add csmtenants access to proxy-server

---

charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/templates/node.yaml
charts/csm-application-mobility/Chart.yaml
charts/csm-application-mobility/values.yaml
installation-wizard/container-storage-modules/Chart.yaml

Yes
https://github.com/dell/csm/issues/1210
https://github.com/dell/csm/issues/1217
Installed powerflex driver with the helm-charts version `release-1.10.1`
Driver is installed and pods are up and running

Release 1.10.1

---

charts/csi-isilon/Chart.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/values.yaml
charts/csm-application-mobility/Chart.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml
charts/karavi-observability/crds/cert-manager.crds.yaml
installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
Updating chart and driver versions for CSM 1.11 

Bump chart driver versions for CSM 1.11

---

charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml

Yes
Updating Observability version for CSM 1.11 

Bump Observability version

---

charts/csm-authorization/crds/csm-authorization.storage.dell.com_csmroles.yaml
charts/csm-authorization/crds/csm-authorization.storage.dell.com_csmtenants.yaml
charts/csm-authorization/crds/csm-authorization.storage.dell.com_storages.yaml

No
Update CRDs for storage, role, and tenant.

Update CRDs for authorization

---

charts/cosi/Chart.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/csm-installer/Chart.yaml
charts/csm-installer/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/crds/cert-manager.crds.yaml
charts/karavi-observability/values.yaml
installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
Bumping the driver/module versions for 10.0.2 release 
- https://github.com/dell/csm/issues/1280

Update driver/module versions for 10.0.2

---

charts/cosi/Chart.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/csm-installer/Chart.yaml
charts/csm-installer/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/crds/cert-manager.crds.yaml
charts/karavi-observability/values.yaml
installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
Bumping driver/module version for release 1.10.2
- https://github.com/dell/csm/issues/1280

Update driver/module versions for  10.0.2

---

charts/csm-authorization/templates/karavi-storage-secret.yaml
charts/csm-authorization/templates/proxy-server.yaml

Remove karavi-storage-secret references.

Remove Karavi Storage Secret

---

charts/cosi/Chart.yaml
charts/cosi/values.yaml
charts/csi-isilon/Chart.yaml
charts/csi-isilon/templates/controller.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/Chart.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/csm-installer/Chart.yaml
charts/csm-installer/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml
installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
https://github.com/dell/csm/issues/1280

Release v1.10.2 rebase resolved

---

charts/csi-powermax/charts/csireverseproxy/Chart.yaml
charts/csi-powermax/charts/csireverseproxy/values.yaml

Yes
https://github.com/dell/csm/issues/1280

Reverse proxy issue

---

charts/csi-vxflexos/values.yaml

No
- https://github.com/dell/csm/issues/1359

Updated SDC Version

---

charts/csi-isilon/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/values.yaml
installation-wizard/container-storage-modules/values.yaml

No
Updates the health monitor sidecar

Update Health Monitor Sidecar

---

charts/csi-isilon/templates/controller.yaml

No
Fix csi-isilon controller yaml.

Removing commented line from csi-isilon controller yaml.

---

charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_csmroles.yaml
charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_csmtenants.yaml
charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_storages.yaml

No
Authorization v2 update storage crd with isiPath for powerscale support
- #Issue_Number https://github.com/dell/csm/issues/1281

Authorization v2 update storage crd with isiPath for powerscale support

---

.github/dependabot.yml

Cherry-picking dependabot config file update for csi-isilon in commit [76e4168d5500670204e3fbae73f903ace41cf497](https://github.com/dell/helm-charts/pull/489/commits/76e4168d5500670204e3fbae73f903ace41cf497)
No
This file drives the dependabot configuration for checking versions of dependencies. The related release branch PR can be found here: https://github.com/dell/helm-charts/pull/489

Adding dependabot compatibility for csi-isilon images

---

charts/karavi-observability/templates/karavi-metrics-powerflex-service-account.yaml
charts/karavi-observability/templates/karavi-metrics-powermax-service-account.yaml
charts/karavi-observability/templates/karavi-metrics-powerscale-service-account.yaml
charts/karavi-observability/templates/karavi-metrics-powerstore-service-account.yaml

No
Add coordination.k8s.io apiGroups access for observability
- [1431](https://github.com/dell/csm/issues/1431)

[charts/karavi-observability] Add coordination.k8s.io apiGroups access for observability

---

.github/dependabot.yml

No
csm-replication
Tested by running helm template --dependency-update charts/csm-replication and manually inspecting the resulting yaml for proper image specifications.

Adding replication dependabot.yml changes

---

.github/dependabot.yml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml
installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes/No
- https://github.com/dell/csm/issues/1478

Rebase 1.11.1

---

.github/dependabot.yml
charts/csm-installer/templates/csm-installer.yaml
charts/csm-installer/values.yaml

No
csm-installer
Tested by inserting mock values in the yaml file for certificates and keys then running helm template --dependency-update charts/csm-installer and manually inspecting the resulting yaml for proper image specifications.
Note: The values.yaml file didn't need updating because it already used image as the value name

[charts/csm-installer] Adding dependabot compatibility for csm-installer images

---

charts/csi-powerstore/values.yaml
charts/csi-vxflexos/values.yaml
installation-wizard/container-storage-modules/values.yaml

No
Updated VGS image version for csm 1.12 in CSM helm chart

charts/container-storage-modules VGS image version update

---

charts/csi-isilon/values.yaml
charts/csi-powermax/values.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization-v2.0/Chart.yaml
charts/csm-authorization-v2.0/charts/redis-csm/values.yaml
charts/csm-authorization-v2.0/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/karavi-observability/values.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
Updates Chart for authorization v1 and v2

[charts/csm-authorization] Version bump for Authorization

---

charts/csi-powerstore/values.yaml
charts/csm-replication/Chart.yaml

No
Updated replication chart and image version
- |https://github.com/dell/csm/issues/1435|

charts/csi-powerstore and charts/csm-replication: updated replication version

---

charts/csi-powermax/values.yaml
charts/csm-replication/values.yaml
installation-wizard/container-storage-modules/values.yaml

No
Noticed that there are some version updates missed in previous PRs. Updating them now.
No tests necessary since this is just an image version update and the versions are yet to be released.

[charts/csm-replication] Updated missed replication versions

---

.github/workflows/rebase-release.yml

No
Fixes reference link.
- https://github.com/dell/csm/issues/1490

Update Sync Release Branch with Main action

---

charts/csi-powermax/charts/csireverseproxy/conf/config.yaml

No
- https://github.com/dell/csm/issues/1567

Remove mode: StandAlone from powermax reverseproxy config.yaml

---

README.md

No
Fixing broken links in Readme
- dell/csm/issues/1635

Fixing broken links in Readme

---

README.md

No
Fixing broken links in Readme
- dell/csm/issues/1635

Rebase with main

---

charts/csi-isilon/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/values.yaml

No
This PR made modifiable values in values.yaml consistent across drivers
- https://github.com/dell/csm/issues/1647

Modifiable values consistent across drivers

---

.github/workflows/charts-release-action.yml
.github/workflows/helm-validations.yml
.github/workflows/kubelinter.yaml
.github/workflows/wizard-release-action.yml
charts/csi-isilon/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization-v2.0/values.yaml
charts/csm-authorization/values.yaml
installation-wizard/container-storage-modules/values.yaml

No
As part of removing release branch requirement, we'll merge what we have so far on the release branch to main since we no longer need this branch for development. All development work will go to main branch going forward.
- https://github.com/dell/csm/issues/1490

Streamline Release Process by Removing Release Branch Requirement

---

charts/csi-isilon/Chart.yaml
charts/csi-isilon/values.yaml
charts/csi-powermax/charts/csireverseproxy/values.yaml
charts/csi-powermax/values.yaml
charts/csi-powerstore/Chart.yaml
charts/csi-powerstore/values.yaml
charts/csi-unity/Chart.yaml
charts/csi-unity/values.yaml
charts/csi-vxflexos/Chart.yaml
charts/csi-vxflexos/values.yaml
charts/csm-authorization-v2.0/Chart.yaml
charts/csm-authorization-v2.0/values.yaml
charts/csm-authorization/Chart.yaml
charts/csm-authorization/values.yaml
charts/csm-replication/Chart.yaml
charts/csm-replication/values.yaml
charts/karavi-observability/Chart.yaml
charts/karavi-observability/values.yaml
installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

No
- https://github.com/dell/csm/issues/1747
Installed Powerscale driver with this helm branch - `upgrade-csm-components-version`
Driver pods running
Ran provisioning test for Powerstore driver

Version bump up for CSM components

---

.github/workflows/charts-release-action.yml
.github/workflows/wizard-release-action.yml

No
Modify the release workflow to checkout to a branch corresponding to the version input. 
For patch releases, we will only release Charts that were modified on the already existing release branch.
- https://github.com/dell/csm/issues/1801

Enable patch releases

---

charts/karavi-observability/templates/karavi-metrics-powerflex-service-account.yaml
charts/karavi-observability/templates/karavi-metrics-powerstore-service-account.yaml

[charts/karavi-observability]: Updating RBAC rules in karavi-observability

---

charts/csi-isilon/templates/controller.yaml
charts/csi-isilon/templates/node.yaml

[charts/csi-powerscale]: Updating RBAC rules in csi-powerscale

---

charts/csi-powerstore/templates/controller.yaml
charts/csi-vxflexos/templates/controller.yaml
charts/csm-replication/templates/controller.yaml

No
(https://github.com/dell/csm/issues/1751)
Testing:
Ran e2e with both sync and async mode. Both of them passed. 
[async_e2e_tests_via_helm_installation.txt](https://github.com/user-attachments/files/19830725/async_e2e_tests_via_helm_installation.txt)
[sync_e2e_tests_via_helm_installation.txt](https://github.com/user-attachments/files/19830726/sync_e2e_tests_via_helm_installation.txt)

[charts/csm-replication]: Updating RBAC rules in csm-replication for Powerstore

---

charts/csi-powermax/templates/controller.yaml
charts/csi-powermax/templates/node.yaml

[charts/csi-powermax]: Updating RBAC rules in csi-powermax

---

charts/csm-authorization-v2.0/templates/authorization-controller.yaml
charts/csm-authorization-v2.0/templates/role-service.yaml
charts/csm-authorization-v2.0/templates/storage-service.yaml

[charts/csi-authorization-v2]: Update RBAC rules

---

charts/csi-isilon/templates/controller.yaml

No
(https://github.com/dell/csm/issues/1751)
Testing:
Ran e2e with async mode using helm installation and repctl. Tests passed successfully.
[e2e_pscale_replication_async_mode_via_repctl.txt](https://github.com/user-attachments/files/19848414/e2e_pscale_replication_async_mode_via_repctl.txt)
[e2e_pscale_replication_async_mode_via_helm.txt](https://github.com/user-attachments/files/19848774/e2e_pscale_replication_async_mode_via_helm.txt)

[charts/csi-isilon]: Updating RBAC rules in csm-replication for Powerscale

---

charts/karavi-observability/templates/karavi-metrics-powerscale-service-account.yaml

[charts/karavi-observability]: Updating RBAC rules in karavi-observability powerscale

---

charts/csm-authorization-v2.0/Chart.yaml
charts/csm-authorization-v2.0/charts/redis-csm/templates/sentinel.yaml
charts/csm-authorization-v2.0/charts/redis-csm/values.yaml
charts/csm-authorization/Chart.yaml

No
The version of ingress-nginx used in authorization deployments is out of date. This PR bumps the version used. 
- https://github.com/dell/csm/issues/1863

[charts/csm-authorization + charts/csm-authorization-v2.0] Update ingress-nginx for Authorization deployments

---

charts/csi-isilon/templates/controller.yaml
charts/csi-powermax/templates/controller.yaml
charts/csi-powerstore/templates/controller.yaml
charts/csi-vxflexos/templates/controller.yaml
charts/csm-replication/templates/controller.yaml

No
This PR updates Replication rules in driver charts
[pflex-replication-e2e.txt](https://github.com/user-attachments/files/20084086/pflex-replication-e2e.txt)
[pscale-replication-e2e.txt](https://github.com/user-attachments/files/20084088/pscale-replication-e2e.txt)
[pmax-replication-e2e.txt](https://github.com/user-attachments/files/20084089/pmax-replication-e2e.txt)

RBAC: Update Replication rules in driver charts

---

charts/csi-powerstore/templates/controller.yaml
charts/csi-powerstore/templates/node.yaml

No
Updates comments from csi-nfs to Shared NFS
- [#1742](https://github.com/dell/csm/issues/1742)

[charts/csi-powerstore]: Update references from csi-nfs to Shared NFS

---

charts/csi-vxflexos/templates/node.yaml
charts/csi-vxflexos/values.yaml

No
This PR exposes the SFTP settings so that it automatically pull the scini.ko kernel module 
[- #Issue_Number](https://github.com/dell/csm/issues/1752)

Helm charts changes for exposing the SFTP settings 

---

charts/csi-vxflexos/values.yaml

Is this a new chart?
No
What this PR does / why we need it:
This PR updates the default value of SFTP settings to false
Which issue(s) is this PR associated with:
https://github.com/dell/csm/issues/1752

Set the SFTP settings to false by default 

---

installation-wizard/container-storage-modules/values.yaml

No
[- #Issue_Number](https://github.com/dell/csm/issues/1752)

installation wizard changes for SFTP

---

index.yaml

updated gh-pages to remove csm 2.14 and powerstore release.

---

charts/csi-powerstore/values.yaml

No
- https://github.com/dell/csm/issues/1742

Patch helm charts to remove references for shared nfs (#729)

---

installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
- https://github.com/dell/csm/issues/1942

[installation-wizard/container-storage-modules] Update 1.14.1 patch

---

installation-wizard/container-storage-modules/Chart.yaml
installation-wizard/container-storage-modules/values.yaml

Yes
Update installation wizard versions for v1.14.1 csi-powerscale
- https://github.com/dell/csm/issues/1991

Update installation wizard versions

---

charts/csi-powerstore/templates/controller.yaml
charts/csi-powerstore/templates/node.yaml

No
Updated environment variables to take authorization enabled true/false. More info: https://github.com/dell/csi-powerstore/pull/547
https://github.com/dell/csm/issues/1947
Updated environment variables to take authorization enabled true/false.

[charts/csi-powerstore] Updated environment variables

---

.github/CODEOWNERS
charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_csmroles.yaml
charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_csmtenants.yaml
charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_storages.yaml

No
We need to update the Auth CRDs to maintain consistency. This is following to an update to controller-gen for csm-authorization.
Relevent PRs for csm-operator and csm-authorization are also in line.

Update Auth v2 CRDs
