- charts/karavi-observability/installer/offline-installer.sh
No
Fixes the URL for the helm repo location in the offline installer script for Karavi-Observability
- #52 
N/A
> Changed helm repo url in offline install script

- charts/karavi-observability/.gitignore
- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/templates/cert-manager.yaml
- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/karavi-topology.yaml
- charts/karavi-observability/templates/otel-collector.yaml
No
Adds cert-manager as a dependency on the karavi-observability chart and creates cert-manager resources to enable ssl cert management for the karavi-observability services.
If no certificates/keys are provided in the values.yaml, cert-manager will automatically use self-signed certs.
- https://github.com/dell/karavi-observability/issues/1
Documentation related to this PR will be added to the dell/karavi-observability repo
> [charts/karavi-observability] Feature cert gen init

- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/otel-collector.yaml
- charts/karavi-observability/values.yaml
No
Makes the otel-collector pod deployed as ClusterIP instead of NodePort
https://github.com/dell/karavi-observability/issues/23
None
> [charts/karavi-observability] BugFix: Removed otel-collector nodeport and revved chart version

- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/templates/karavi-topology.yaml
- charts/karavi-observability/values.yaml
No
This PR is to create config files in /etc/config named karavi-metrics-powerflex.yaml and karavi-topology.yaml , which contains parameters that can be modified while running the karavi-observability services. The config files will be created during the helm install. 
- [dell/karavy-observability#25](https://github.com/dell/karavi-observability/issues/25)
> Create configmaps to replace environment variables

- .github/workflows/helm-validations.yml
Remove GITHUB_BASE_REF dependency
No
This PR  removes the GITHUB_BASE_REF dependency for skipping helm lint tests. Without this change, PR whose base ref isn't master will 'randomly' fail or act abnormally. 
- [#27](https://github.com/dell/karavi-observability/issues/27)
> Remove GITHUB_BASE_REF dependency

- charts/karavi-observability/templates/NOTES.txt
- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/values.yaml
No
Removes the Secret that contains the PowerFlex endpoint and credentials. Adds a new volume mount for the vxflexos-config Secret that will be copied from the PowerFlex CSI driver namespace to be used with Karavi Observability.
- https://github.com/dell/karavi-observability/issues/30
> Use secret from the csi-vxflexos driver

- charts/karavi-observability/values.yaml
No
On OpenShift, the nginx:1 image fails with an error `nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)`. The fix is to use the unprivileged version of the image.
- Sucessfully ran e2e against k8s 1.20
- Successfully ran e2e against Openshift 4.6
- https://github.com/dell/helm-charts/issues/54
> Update nginx image to be compatible with OpenShift

- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/values.yaml
No
This adds 2 new properties to the topology and metrics-powerflex services to support setting the log level (e.g. debug, info, warn, error, etc) and log format (e.g. text, json).
- https://github.com/dell/karavi-observability/issues/43
> Added log level and format to configmaps for topology and metrics-powerflex

- charts/karavi-observability/values.yaml
No
Add PowerStore CSI in default Provisioners for Topology Service
- #https://github.com/dell/karavi-observability/issues/58
> Support powerstore volumes in topology service

- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/templates/karavi-topology.yaml
- charts/karavi-observability/values.yaml
No
This PR will add support for golang profiling and zipkin support for topology service.
- #https://github.com/dell/karavi-observability/issues/58
> Add support for zipkin and golang profile in topology service

- .github/workflows/helm-validations.yml
- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/values.yaml
No
The authorization sidecar is now deployed via helm in karavi-metrics-powerflex.
[112](https://github.com/dell/csm/issues/112)
112
> feature-112: Deprecate injection

- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/karavi-metrics-powerstore.yaml
- charts/karavi-observability/templates/karavi-topology.yaml
No
It replaces the  `app.kubernetes.io/name`  with `name` of the application.
It is better to be consistent between these and generally speaking the [names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) should be compatible with DNS names (i.e. no `_` accepted).
[dell/csm/#186](https://github.com/dell/csm/issues/186)
> [charts/karavi-observability] Make `app.kubernetes.io/name` and `name` consistent

- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/otel-collector-config.yaml
- charts/karavi-observability/values.yaml
No
With upcoming updates to the otel-collector and all of the otel packages in the various observability repos the otel-collector config needed to be updated according to upstream changes to the collector.
None
I have run e2e tests with this config change successfully:
```
--- PASS: Test_Metrics (58.55s)
--- PASS: Test_Metrics/Powerflex_Volume_Metrics (14.19s)
--- PASS: Test_Metrics/Powerflex_Storage_Pool (14.17s)
--- PASS: Test_Metrics/Powerflex_ExportNode_Metrics (30.18s)
PASS
ok      karavi-testing/karavi-metrics/metrics-test      58.584s
--- PASS: Test_Query_Topology (14.17s)
PASS
ok      karavi-testing/karavi-topology/topology-test    14.197s
--- PASS: Test_Metrics (246.54s)
--- PASS: …
```
> [charts/karavi-observability] Updated otel-collector and cert manager for observability helm chart

- .github/workflows/helm-validations.yml
- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/charts/redis/templates/redis.yaml
- charts/csm-authorization/templates/ingress.yaml
- charts/csm-authorization/values.yaml
No
This PR allows users to optionally deploy the cert-manager and ingress controller dependencies. Since the ingresses could be registered with an existing ingress controller, the user now has control over each ingress's class name, host rules, and annotations. 
Redis is configured to use the default storage class (by not providing a `storageClassName` in the redis pvc) if no redis.storageClass is specified in the values.
https://github.com/dell/csm/issues/261
This was tested manually by deploying the chart in various configurations with dependencies.
> [charts/csm-authorization]: Conditional dependencies

- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/values.yaml
No
PR to upgrade the helm chart and metrics images to v1.1.1
[- #Issue_Number](https://github.com/dell/csm/issues/279)
> charts/karavi-observability: Patch v1.1.1 updates

- charts/karavi-observability/otel-collector-config.yaml
- charts/karavi-observability/values.yaml
No
Reverts the OTEl version to fix the issue with displaying metrics in Grafana
- [#288](https://github.com/dell/csm/issues/288)
> karavi-observability: Reverting OTEL version for patch 1.1.1

- charts/karavi-observability/otel-collector-config.yaml
- charts/karavi-observability/values.yaml
No
This PR reverts Otel version for Observability patch v1.1.1
- #[288](https://github.com/dell/csm/issues/288)
> karavi-observability: Revert OTEL changes for patch v1.1.1

- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/values.yaml
Yes
Update the Observability Chart to point to newly released v1.2.0 images.
N/A
Performed manual inspection of the Grafana UI to verify that the dashboards properly show data while generating I/O and storage resources.
> [charts/karavi-observability] Updates for release v1.2.0

- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/values.yaml
No
enable PowerScale topology
- #334: https://github.com/dell/csm/issues/334
This code change has been verified along with changes in karavi-topology [PR#116](https://github.com/dell/karavi-topology/pull/116)
> add support for PowerScale topology

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/policies/url.rego
- charts/csm-authorization/values.yaml
No
- Changes the default behavior of the csi-powerflex url paths policy to allow all paths by default. 
- Since the nginx-controller is enabled by default, we should enable the relevant ingressClassName and annotations by default.
https://github.com/dell/csm/issues/353
> [csm-authorization]: allow all powerflex paths and change default values

- charts/karavi-observability/otel-collector-config.yaml
- charts/karavi-observability/values.yaml
No
Rollback otel-collecter and nginxProxy image version to 0.42.0 and 1.20;
Rollback tls settings for otel in otel-collector-config.yaml.
- #356: https://github.com/dell/csm/issues/356
- This code change has been verified along with changes in karavi-metrics-powerflex [PR#130](https://github.com/dell/karavi-metrics-powerflex/pull/130)
- Rollback otel-collecter image version to 0.42.0, because we upgrade the OpenTelemetry to v1.7.0 in karavi-metrics-powerflex, and its async UpDownCounter is working well to fetch the “current value”.
> Rollback otel-collecter image version to 0.42.0

- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/values.yaml
No
Adjust new enable and frequency for PowerScale as below:
capacityMetricsEnabled: "true"
performanceMetricsEnabled: "true"
clusterCapacityPollFrequencySeconds: 30
clusterPerformancePollFrequencySeconds: 20
quotaCapacityPollFrequencySeconds: 30
- #377: https://github.com/dell/csm/issues/377
> [charts/karavi-observability] Adjust PowerScale polling enable and frequency

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/templates/policies.yaml
- charts/csm-authorization/templates/proxy-server.yaml
No
Typo in the powerscale-volumes-create rego file which causes volume creating requests to be denied.
Updates the opa-configmap-modifier RoleBinding to be in the release namespace instead of hardcoded to karavi.
- [#419](https://github.com/dell/csm/issues/419)
> [charts/csm-authorization]: Fix powerscale volume create policy and fix rolebinding

- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/karavi-metrics-powerscale.yaml
- charts/karavi-observability/values.yaml
No
enable authorization for csm observability powerscale
- #413: https://github.com/dell/csm/issues/413
To enable authorization for csm observability powerscale, and To **keep compatibility** with authorization of csm observability powerflex, please run below commands to copy/rename configmap and secrets from isilon namespace to karavi namespace:
1. `kubectl get configmap isilon-config-params -n isilon -o yaml | sed 's/namespace: isilon/namespace: karavi/' | kubectl create -f -`
2. `kubectl get secret karavi-authorization-config proxy-server-root-certificate proxy-authz-tokens -n isilon -o yaml | sed 's/namespace: isilon/namespace: karavi/' | sed 's/name: karavi-authorization-config/name: isilon-karavi-authorization-config/' | sed 's/name: proxy-server-root-certificate/name: …
> enable authorization for csm observability powerscale

- charts/karavi-observability/values.yaml
No
Update Authorization sidecar to latest 1.4.0 image
| https://github.com/dell/csm/issues/350 |
> Update Authorization sidecar image to 1.4.0

- .github/CODEOWNERS
- charts/karavi-observability/Chart.yaml
- charts/karavi-observability/otel-collector-config.yaml
- charts/karavi-observability/templates/NOTES.txt
- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/karavi-metrics-powerscale-service-account.yaml
- charts/karavi-observability/templates/karavi-metrics-powerscale.yaml
- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/values.yaml
Yes
- #https://github.com/dell/csm/issues/452
- #https://github.com/dell/csm/issues/453
- #https://github.com/dell/csm/issues/454
> charts/karavi-observability Karavi observability release v1.3.0

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/policies/url.rego
- charts/csm-authorization/templates/policies.yaml
- charts/csm-authorization/templates/proxy-server.yaml
- charts/csm-authorization/values.yaml
> [charts/csm-authorization]: Minor fixes for 1.4.0

- charts/karavi-observability/values.yaml
No
Updates Authorization sidecar image for the CSM 1.5 release.
- https://github.com/dell/csm/issues/491 
> [charts/karavi-observability]: Update Authorization sidecar for 1.5 release

- charts/csm-encryption-rekey-controller/Chart.yaml
- charts/csm-encryption-rekey-controller/README.md
- charts/csm-encryption-rekey-controller/templates/controller.yaml
- charts/csm-encryption-rekey-controller/templates/rekey-crd.yaml
- charts/csm-encryption-rekey-controller/values.yaml
Yes
Adds a Helm chart that installs a CRD controller which supports CSM Encryption rekey functionality.
- [#491](https://github.com/dell/csm/issues/491)
> [charts/csm-encryption-rekey-controller]: technical preview v0.1.0

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/templates/csm-config-params.yaml
- charts/csm-authorization/values.yaml
No
Adds the `concurrentPowerFlexRequests` setting in the values to configure the number of concurrent requests to PowerFlex in the storage-service. This is also configurable in the csm-config-params configMap after installation.
https://github.com/dell/csm/issues/408
> [charts/csm-authorization]: Concurrent PowerFlex requests in the storage-service

- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/values.yaml
No
Rename arrayCapacityPollFrequencySeconds to capacityPollFrequencySeconds to support capacity metrics for Observability PowerMax
- #https://github.com/dell/csm/issues/586
> Rename arrayCapacityPollFrequencySeconds to capacityPollFrequencySeconds

- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/values.yaml
No
Rename the performance poll frequency
- https://github.com/dell/csm/issues/586
> Rename the performance poll frequency

- charts/csm-authorization/policies/volumes-create.rego
- charts/csm-authorization/policies/volumes-powermax-create.rego
No
Updates volume create policies to allow zero quota.
https://github.com/dell/csm/issues/654
> [charts/csm-authorization]: Update volume create policies for zero quota

- charts/csm-authorization/values.yaml
No
This PR updates the version for csm-authorization
| https://github.com/dell/csm/issues/583 |
> Auth version update to 1.6.0

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/templates/NOTES.txt
- charts/csm-authorization/templates/certificate.yaml
- charts/csm-authorization/templates/ingress.yaml
- charts/csm-authorization/values.yaml
No
This PR removes the tenant-service ingress because `karavictl` will now be sending requests to the proxy-server.
https://github.com/dell/csm/issues/725
> [charts/csm-authorization]: feature-725: Remove tenant service ingress

- charts/container-storage-modules/Chart.yaml
- charts/csi-unity/Chart.yaml
- charts/csi-unity/templates/_helpers.tpl
- charts/csi-unity/values.yaml
[charts/csi-unity] : 2.7.0 csi-unity support for helm in csm-installation-wizard
No
To support csi-unity-driver 2.7.0
Tested using both csm-installation-wizard ui and the helm way of installation.
> [charts/csi-unity] : 2.7.0 csi-unity support for helm in csm-installation-wizard

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/templates/_helpers.tpl
- charts/container-storage-modules/values.yaml
No
Removed unused dependencies from container-storage-modules helm chart
> Removed unused dependencies from container-storage-modules helm chart

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-powerstore/templates/_helpers.tpl
- charts/csi-powerstore/values.yaml
No
It is to support CSI-PowerStore 2.7.0 driver
> [charts/csi-powerstore] Added PowerStore 2.7.0 Support

- charts/container-storage-modules/values.yaml
- charts/csi-powerstore/templates/_helpers.tpl
- charts/csi-powerstore/values.yaml
No
Update sidecars version and csi-metadata-retriever version for Powerstore v2.7.0
> [charts/csi-powerstore] Sidecars and csi-metadata-retriever version update

- charts/karavi-observability/templates/karavi-metrics-powerflex.yaml
- charts/karavi-observability/templates/karavi-metrics-powermax-service-account.yaml
- charts/karavi-observability/templates/karavi-metrics-powermax.yaml
- charts/karavi-observability/templates/karavi-metrics-powerscale.yaml
- charts/karavi-observability/templates/karavi-metrics-powerstore.yaml
- charts/karavi-observability/templates/karavi-observability-configmap.yaml
- charts/karavi-observability/templates/karavi-topology.yaml
- charts/karavi-observability/templates/otel-collector.yaml
- charts/karavi-observability/values.yaml
No
- #https://github.com/dell/csm/issues/743
> reverting observability

- charts/csi-powermax/templates/_helpers.tpl
- charts/csi-powermax/templates/controller.yaml
- charts/csi-powermax/templates/csidriver.yaml
- charts/csi-powermax/values.yaml
Yes/No
Support StorageCapacityTracking feature for PowerMax.
Additional context
This feature helps the scheduler to schedule the pod on a node (satisfying the topology constraints) only if the requested capacity is available on the storage array.
https://github.com/dell/csm/issues/876
https://github.com/dell/csm/issues/876
> StorageCapacityTracking feature changes

- charts/csm-replication/templates/controller.yaml
- charts/csm-replication/values.yaml
No
Updating csm-replication charts for changes in PR https://github.com/dell/csm-replication/pull/104
- https://github.com/dell/csm/issues/885
> [charts/csm-replication]: Updates for removing init container usage

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
- charts/csi-vxflexos/Chart.yaml
- charts/csi-vxflexos/templates/_helpers.tpl
- charts/csi-vxflexos/templates/controller.yaml
- charts/csi-vxflexos/templates/csidriver.yaml
- charts/csi-vxflexos/templates/node.yaml
- charts/csi-vxflexos/values.yaml
Yes/No
PowerFlex v2.8.0 release
https://github.com/dell/csm/issues/885
> PowerFlex v2.8.0 release

- charts/container-storage-modules/values.yaml
- charts/csi-vxflexos/values.yaml
Yes/No
PowerFlex  SDC  updated
https://github.com/dell/csm/issues/885
> PowerFlex  SDC  updated

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
- charts/csi-powermax/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/values.yaml
- charts/csi-powermax/templates/_helpers.tpl
- charts/csi-powermax/values.yaml
No
Adding k8 28 support for powermax
Updating helm/driver version 
- https://github.com/dell/csm/issues/947
> Adding k8 28 support for powermax

- charts/csi-unity/Chart.yaml
- charts/csi-unity/templates/_helpers.tpl
No
It adds 1.28 k8s support in CSI Unity Driver
- https://github.com/dell/csm/issues/947
> K8s 1.28 support unity

- charts/csi-vxflexos/values.yaml
No
Its about a minor typo fix.
- https://github.com/dell/csm/issues/763#Issue_Number
> minor typo fixed

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-powerstore/templates/_helpers.tpl
- charts/csi-powerstore/values.yaml
No
It adds support for PowerStore v2.8 and k8s 1.28
- https://github.com/dell/csm/issues/947
- https://github.com/dell/csm/issues/885
> PowerStore v2.8.0 & k8s 1.28 support

- charts/container-storage-modules/values.yaml
- charts/csi-powerstore/templates/node.yaml
- charts/csi-powerstore/values.yaml
No
For supporting volume limits feature in CSIPowerstore
| https://github.com/dell/csm/issues/876|
Set maxPowerStoreVolumesPerNode to 1 in values.yaml and installed the driver
Driver installed successfully:
Env var set:
Tried to schedule 3 volumes, only 2 volumes scheduled successfully as expected:
> Powerstore volume limits

- charts/csi-powerstore/templates/node.yaml
No
For removing duplicate entry X_CSI_DRIVER_NAME in node.yaml for CSI Powerstore
- https://github.com/dell/csm/issues/877
> charts/csi-powerstore Removed duplicate entry for X_CSI_DRIVER_NAME in node.yaml for CSI Powerstore

- charts/container-storage-modules/values.yaml
- charts/csi-isilon/values.yaml
- charts/csi-powermax/values.yaml
- charts/csi-powerstore/values.yaml
- charts/csi-unity/values.yaml
- charts/csi-vxflexos/values.yaml
- charts/csm-authorization/Chart.yaml
- charts/karavi-observability/values.yaml
No
This PR updates the version for csm-authorization to 1.8 and podmon to 1.7
- [#885](https://github.com/dell/csm/issues/885)
> update auth to 1.8

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
- charts/csi-isilon/values.yaml
- charts/csi-powermax/values.yaml
- charts/csi-powerstore/values.yaml
- charts/csi-vxflexos/values.yaml
- charts/csm-replication/Chart.yaml
- charts/csm-replication/values.yaml
No
Updated replication-controller image to v1.6.0 and replicator/migrator/rescanner side car versions.
- https://github.com/dell/csm/issues/885
> [charts/csm-replication]: Updated image versions for CSM v1.8.0

- charts/csi-powerstore/templates/csidriver.yaml
No
As part of Openshift 4.13 support in CSI Powerstore, an extra label "security.openshift.io/csi-ephemeral-volume-profile" needs to be added in CSIDriver;s yaml for supporting inline ephemeral volumes.
https://docs.openshift.com/container-platform/4.13/storage/container_storage_interface/ephemeral-storage-csi-inline.html
|https://github.com/dell/csm/issues/724|
Ran cert-csi for ephemeral volume suite:
> Adding CSI Powerstore driver’s effective pod security profile for supporting ephemeral volumes as part of Openshift 4.13 support

- charts/container-storage-modules/Chart.yaml
No
Updated chart version for container-storage-modules helm chart 
> charts/container-storage-modules: Updated chart version

- charts/csi-vxflexos/templates/controller.yaml
- charts/csi-vxflexos/values.yaml
No
this pr addresses the removal of redundant parameter i.e external Access.
> [charts/csi-vxflexos]:2.8.0 removed externalAccess from csi-vxflexos manifests.

- charts/csi-powerstore/templates/csidriver.yaml
Reverts dell/helm-charts#261 as we have already taken this issue in "Known Issues"
> Revert "Adding CSI Powerstore driver’s effective pod security profile for supporting ephemeral volumes as part of Openshift 4.13 support"

- charts/container-storage-modules/values.yaml
No
PR to uncomment resiliency controller and node arguments.
- https://github.com/dell/csm/issues/959
> [charts/container-storage-modules]: Uncomment Resiliency arguments

- charts/cosi/templates/_helpers.tpl
No
Correct validating the `.Values.provisioner.logLevel`
N/A
> [charts/cosi] correct cosi log level setting

- charts/container-storage-modules/values.yaml
- charts/csi-powerstore/values.yaml
- charts/csi-vxflexos/values.yaml
No
Updated csi-volumegroup-snapshotter version
https://github.com/dell/csm/issues/885
> [charts/container-storage-modules] Bumped csi-volumegroup-snapshotter version

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
No
This PR will reset the Container storage modules helm chart changes to main branch changes to avoid the failures during the release due to dependency issues. 
PR with release1.8 changes has been created. https://github.com/dell/helm-charts/pull/294
> Chart/Container-Storage-Modules Reset the CSM helm chart to main branch

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-powerstore/templates/_helpers.tpl
- charts/csi-powerstore/values.yaml
> [charts/csi-powerstore] Add PowerStore v2.9.0 support & sidecar version update

- charts/cosi/Chart.yaml
No
Current chart on the helm repo has wrong image reference
I bumped the chart version only and not the driver image as the driver is the same
> [charts/cosi] Bump chart version to use the correct docker image

- charts/csi-powermax/values.yaml
Yes/No
Updating latest sidecar versions for Powermax driver 
> Updating latest sidecars for Powermax

- charts/csi-vxflexos/templates/node.yaml
No
Adding noderoot mount path to access root directory of the host from the node pod. We need this to run query_mdm command from the node pod on the worker host when driver calls the goscaleio call DrvCfgQuerySystems to fetch all the system ID's configured.
- https://github.com/dell/csm/issues/1020
> [charts/csi-powerflex] Adding noderoot mount path

- charts/container-storage-modules/values.yaml
- charts/csi-vxflexos/templates/controller.yaml
- charts/csi-vxflexos/values.yaml
No
Added external access parameter which is required to provide to external network/ip to the NFS export hosts.
- https://github.com/dell/csm/issues/1011
> [charts/csi-powerflex] Added external access

- charts/container-storage-modules/Chart.yaml
- charts/container-storage-modules/values.yaml
No
This PR will reset the Container storage modules helm chart changes to main branch changes to avoid the failures during the release due to dependency issues. 
PR with release1.9 changes has been created. https://github.com/dell/helm-charts/pull/339
> Reset CSM to release v1.9.0 to main

- charts/csi-vxflexos/templates/node.yaml
No
This PR includes addition of env X_CSI_POWERFLEX_KUBE_NODE_NAME that is required in the PowerFlex driver to fetch the node labels.
- https://github.com/dell/csm/issues/1086
> [charts/csi-powerflex] Added env for kube node name

- charts/csm-authorization/crds/csm-authorization.storage.dell.com_csmtenants.yaml
No
This PR adds CSMTenant CRD into Authorization helm chart.
- Stateless-rearchitecture
> [charts/csm-authorization] Add CSMTenant CRD into Authorization chart

- charts/cosi/Chart.yaml
- charts/cosi/values.yaml
No
COSI image was not updated for CSM 1.9. Correcting this with this PR.
> [charts/cosi] Image update

- charts/csm-authorization/charts/redis/templates/redis.yaml
- charts/csm-authorization/templates/ingress.yaml
- charts/csm-authorization/values.yaml
No
It enables access to the proxy-server by the IP address of the cluster master node instead of requiring access by one of the hostnames configured in the Ingress.
This also configures a local provisioner for Redis to use by default so the user does not have to worry about what storage class to use for Redis. They can still provide a storage class if they wish.
https://github.com/dell/csm/issues/1091
> [feature-1091]: Expose proxy-server via cluster node IP and use local storage for Redis by default

- charts/container-storage-modules/values.yaml
- charts/csi-powermax/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/values.yaml
- charts/csi-powermax/values.yaml
Yes
Bumping reverseproxy version for 1.10
- https://github.com/dell/csm/issues/1091
> Bumping reverseproxy version for 1.10

- charts/cosi/Chart.yaml
- charts/cosi/values.yaml
No
- #(https://github.com/dell/csm/issues/1091)
> Cosi driver version update for CSM 1.10

- charts/csm-application-mobility/Chart.yaml
- charts/csm-application-mobility/values.yaml
No
This PR bumps the version of app mobility.
https://github.com/dell/csm/issues/1091
> `[charts/csm-application-mobility]`  Version Bump

- charts/csi-isilon/values.yaml
- charts/csi-powermax/values.yaml
- charts/csi-powerstore/values.yaml
- charts/csi-unity/values.yaml
- charts/csi-vxflexos/values.yaml
No
Change default value comment of KUBELET_CONFIG_DIR from None to /var/lib/kubelet.
https://github.com/dell/csm/issues/1174
> [bug-1174]: Update kubeletConfigDir comment

- charts/csm-application-mobility/Chart.yaml
- charts/csm-application-mobility/values.yaml
No
Reverting the recent app mobility version back to 0.3.0
- N/A
> [csm-application-mobility] Revert app mobility version changes

- charts/csi-unity/Chart.yaml
- charts/csi-unity/templates/node.yaml
- charts/csi-unity/values.yaml
No
Mechanism for selecting custom networks for array traffic in `csi-unity`.
- https://github.com/dell/csm/issues/1222
Chart was manually tested - installed with and without parameter `allowedNetworks`
> `[charts/csi-unity]` fix: add allowedNetworks parameter

- charts/csi-isilon/Chart.yaml
- charts/csi-powermax/Chart.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-unity/Chart.yaml
- charts/csi-vxflexos/Chart.yaml
Yes
This PR allows to install the CSI drivers on a Kubernetes version that is above the internally tested one
- KRV-13492
`helm lint` passed and this has been tested with csi-powerflex only
> Remove check on maximum version of kube

- charts/csm-authorization/templates/role-service.yaml
No
PR to remove storage service from the role service as it is no longer needed.
> Cleanup role service

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/templates/ingress.yaml
- charts/csm-authorization/values.yaml
No
Adds openshift default ingress support
> Use default openshift ingress

- charts/csm-authorization/templates/csm-config-params.yaml
- charts/csm-authorization/values.yaml
No
Added new parameter for storage capacity polling interval for csm-authorization
> [KRV-21812] Storage capacity poll interval

- charts/cosi/Chart.yaml
- charts/cosi/values.yaml
- charts/csi-isilon/values.yaml
- charts/csi-powerstore/values.yaml
- charts/csm-application-mobility/Chart.yaml
- charts/csm-application-mobility/values.yaml
- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/values.yaml
- charts/karavi-observability/values.yaml
- installation-wizard/container-storage-modules/values.yaml
Yes
Upgrading module chart/version.
> Bump the module versions

- charts/csm-authorization/templates/storage-service.yaml
- charts/csm-authorization/values.yaml
No
Makes Vault authentication role configurable.
> Add Vault authentication role to values

- charts/csm-authorization/charts/redis/templates/redis-secret.yaml
- charts/csm-authorization/charts/redis/templates/redis.yaml
No
Add login username and password to rediscommander web portal so that it's not exposed to anyone on the cluster.
- [#1281](https://github.com/dell/csm/issues/1281)
> [csm-authorization/redis] Add username and password to rediscommander

- charts/csi-isilon/templates/controller.yaml
No
removed extra space from sidecar suffix
- https://github.com/dell/csm/issues/1280
> removed extra space from sidecar suffix

- charts/csm-authorization/charts/redis/templates/sentinel.yaml
No
Sentinel pod deployment occasionally cycles through all redis pods even before they come up and then fails.
Adding retry logic in sentinel deployment (init container) to keep checking for redis pods with a delay of 30s if all redis pods have been checked and none of them are ready.
This is not consistently reproducible and it depends on the particular environment when this manifests. The retry logic added should help.
https://github.com/dell/csm/issues/1281
The changes are only in the init container deployment of sentinel pods, its a minor change to beef up the retry logic.
> Add retry logic for sentinel start-up

- .github/workflows/charts-release-action.yml
- .github/workflows/helm-validations.yml
- .github/workflows/kubelinter.yaml
- .github/workflows/wizard-release-action.yml
- .github/workflows/yamllinter.yaml
- .yamllint
No
We need it for verifying whether our yaml files are properly formatted.
- [#1303](https://github.com/dell/csm/issues/1303)
> Add yaml lint GitHub Action

- charts/csm-authorization/charts/redis/Chart.yaml
- charts/csm-authorization/charts/redis/templates/redis.yaml
- charts/csm-authorization/charts/redis/templates/sentinel.yaml
- charts/csm-authorization/charts/redis/values.yaml
- charts/csm-authorization/values.yaml
1. Fix sentinel deployment timeout issue noticed on some setups. Generalized the checks in bash. 
2. Organize sub-charts for redis to be able to independently deployable, ensure root values take precedence over sub-chart values.
Yes
See above
https://github.com/dell/csm/issues/1281
> Fix sentinel timeout issue, organize subcharts for redis

- .github/workflows/helm-validations.yml
- .yamllint
- ct.yaml
- dependencyConfig.yaml
- lintConfig.yaml
No
Updates helm-validations action to run helm lint on charts under the charts directory and removes configurations no longer used in the action. 
Linting errors addressed in https://github.com/dell/helm-charts/pull/450.
Example output of linter:
```
Run ct lint --config ct.yaml
Linting charts...
------------------------------------------------------------------------------------------------------------------------
Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
csi-powermax => (version: "2.10.2", path: "charts/csi-powermax")
------------------------------------------------------------------------------------------------------------------------
Saving 1 charts
Dependency csireverseproxy did …
```
> Update helm chart validation action

- charts/csm-authorization/charts/redis/templates/sentinel.yaml
Yes
Sentinel statefulset deployments failed on certain environments due to variance in the versions of shell. The == operator evaluated to = in some shells but not all of them. Fix is to use single = in comparisons. 
> Fix Sentinel stateful set deployment

- charts/csm-authorization/templates/authorization-controller.yaml
- charts/csm-authorization/values.yaml
Yes
Add configurable authorization controller reconcile interval.
- https://github.com/dell/csm/issues/1281
> Add configurable controller reconcile interval

- charts/csi-powermax/templates/controller.yaml
- charts/csi-powermax/templates/node.yaml
- charts/csi-powermax/values.yaml
No
- Podmon installation with the driver
- https://github.com/dell/csm/issues/1082
> Powermax resiliency changes

- charts/csi-isilon/templates/controller.yaml
Do not install additional instance of retriever when Encryption is enabled.
No
Do not install additional instance of retriever when Encryption is enabled.
[1309](https://github.com/dell/csm/issues/1309)
> csi-isilon: second csi-metadata-retriever instance eliminated

- charts/csi-unity/values.yaml
No
- https://github.com/dell/csm/issues/1335
Driver pods running:
> [charts/csi-unity] Update usage of allowedNetworks in values.yaml

- charts/csi-isilon/Chart.yaml
- charts/csi-powermax/Chart.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-unity/Chart.yaml
- charts/csi-vxflexos/Chart.yaml
Update Helm chart to remove warning in Chart.yaml
No
Removed a warning presented in Chart files. Unsupported (alpha/beta) versions are checked for in the installer and prompted for user confirmation
Removed a warning presented in Chart files. Unsupported (alpha/beta) versions are checked for in the installer and prompted for user confirmation
https://github.com/dell/csm/issues/1325
> Removed warning from Chart

- charts/csi-isilon/templates/controller.yaml
Add the patch verb to volumesnapshotcontents/status to fix snapshot creation.
No
This PR adds a missing permission to Isilon controller. Without it, snapshots cannot be taken 
[- #1340](https://github.com/dell/csm/issues/1340)
> csi-isilon: add the patch verb to volumesnapshotcontents/status to fix snapshot creation.

- charts/csm-authorization/Chart.yaml
- charts/csm-authorization/charts/redis/Chart.yaml
- charts/csm-authorization/charts/redis/templates/_helpers.tpl
- charts/csm-authorization/charts/redis/templates/redis-cm.yaml
- charts/csm-authorization/charts/redis/templates/redis-secret.yaml
- charts/csm-authorization/charts/redis/templates/redis.yaml
- charts/csm-authorization/charts/redis/templates/sentinel.yaml
- charts/csm-authorization/charts/redis/values.yaml
- charts/csm-authorization/crds/csm-authorization.storage.dell.com_csmroles.yaml
- charts/csm-authorization/crds/csm-authorization.storage.dell.com_csmtenants.yaml
- charts/csm-authorization/crds/csm-authorization.storage.dell.com_storages.yaml
- charts/csm-authorization/policies/snapshot-create-test.rego
- charts/csm-authorization/policies/snapshot-create.rego
- charts/csm-authorization/templates/authorization-controller.yaml
- charts/csm-authorization/templates/csm-config-params.yaml
- charts/csm-authorization/templates/ingress.yaml
- charts/csm-authorization/templates/policies.yaml
- charts/csm-authorization/templates/proxy-server.yaml
- charts/csm-authorization/templates/role-service.yaml
- charts/csm-authorization/templates/storage-service.yaml
- charts/csm-authorization/templates/tenant-service.yaml
- charts/csm-authorization/values.yaml
No
CSM Authorization v2
https://github.com/dell/csm/issues/1281
> [charts/csm-authorization]: CSM Authorization v2

- charts/csi-powerstore/values.yaml
No
Making default value of allowAutoRoundOffFilesystemSize param for powerstore true. So that the non-supported min size volume provisioning won't fail. 
- https://github.com/dell/csm/issues/1377
> Setting allowAutoRoundOffFilesystemSize param to true

- charts/csi-powerstore/templates/controller.yaml
Yes/No
Making default value of allowAutoRoundOffFilesystemSize param for powerstore true. So that the non-supported min size volume provisioning won't fail.
- https://github.com/dell/csm/issues/1377
> make roundoff_file_system param default to true

- charts/csm-authorization/templates/csm-config-params.yaml
- charts/csm-authorization/values.yaml
No
- PR for extending the dellctl support for Powerscale
- [https://github.com/dell/csm/issues/1281]
The deployment of stateless Authorization is successful with these changes - 
```
[root@master-1-20JuIZwsvfcbQ helm-charts]# kubectl get pods -n authorization
NAME                                                      READY   STATUS    RESTARTS        AGE
authorization-cert-manager-5b89d78568-l62s2               1/1     Running   0               5m42s
authorization-cert-manager-cainjector-76565fdd85-r29z8    1/1     Running   0               5m42s
authorization-cert-manager-webhook-5f89d985b5-tfrbw       1/1     Running   0               5m42s
authorization-controller-59f9dbf6b6-cn5bs                 1/1     Running   0               5m42s …
```
> dellctl support for Powerscale

- charts/csi-powermax/values.yaml
- installation-wizard/container-storage-modules/values.yaml
No
I noticed that migrator and node-rescanner image versions need an update for CSM 1.11 release. Previously pointed out versions have already been released. Last PR for reference - https://github.com/dell/helm-charts/pull/407
https://hub.docker.com/repository/docker/dellemc/dell-csi-replicator/general
https://hub.docker.com/repository/docker/dellemc/dell-csi-migrator/general
https://hub.docker.com/repository/docker/dellemc/dell-csi-node-rescanner/general
No tests necessary since this is just an image version update and the versions are yet to be released.
> [charts/csi-powermax] Updated migrator and node-rescanner versions with correct versions for 1.11

- charts/csm-application-mobility/Chart.yaml
- charts/csm-application-mobility/values.yaml
No 
Fix defect in helm charts- AM 0.4 does not exist. 
N/A 
Installed w/ new charts, verified it worked:
```
[root@master-1-bSUpXC4r0a0EU csm-license]# kubectl get pods -n application-mobility
NAME                                                       READY   STATUS    RESTARTS   AGE
application-mobility-controller-manager-5b5ddfbcf7-jf9fg   2/2     Running   0          13s
application-mobility-velero-58cdc99ddc-fv98s               1/1     Running   0          11m
restic-6qjhr                                               1/1     Running   0          11m
restic-mgfd2                                               1/1     Running   0          11m
```
> [charts/csm-application-mobility] Fix am charts

- charts/csi-isilon/values.yaml
- charts/csm-encryption-rekey-controller/values.yaml
No
Updated Encryption Driver and Rekey Controller versions for 1.11
No tests necessary since this is just an image version update and the versions are yet to be released.
> [Encryption] Updated Encryption Driver and Rekey Controller versions for 1.11

- charts/csi-isilon/Chart.yaml
- charts/csi-powermax/Chart.yaml
- charts/csi-powermax/templates/node.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-unity/Chart.yaml
- charts/csi-vxflexos/Chart.yaml
- charts/csm-installer/Chart.yaml
- charts/csm-replication/values.yaml
- installation-wizard/container-storage-modules/values.yaml
No
Address PR comments for "Release v1.11.0" in #469.
> Address PR comments for "Release v1.11.0"

- charts/csm-authorization-v2.0/crds/csm-authorization.storage.dell.com_storages.yaml
- charts/csm-authorization-v2.0/templates/csm-config-params.yaml
- charts/csm-authorization-v2.0/templates/storage-service.yaml
- charts/csm-authorization-v2.0/values.yaml
- charts/csm-authorization/templates/storage-service.yaml
No
- Supports multiple vault configurations during deployment
- kvEnginePath now configurable in storage CR
- Adds concurrent powerscale requests
Storage CR sample:
```
apiVersion: csm-authorization.storage.dell.com/v1alpha1
kind: Storage
metadata:
name: powerflex
spec:
type: powerflex
endpoint: https://127.0.0.1
systemID: 1a99aa999999aa9a
vault:
identifier: vault0
kvEngine: secret
path: powerflex/1a99aa999999aa9a
skipCertificateValidation: true
pollInterval: 30s
```
- https://github.com/dell/csm/issues/1281
> [charts/csm-authorization-v2.0] Support multiple instances of vault

- charts/csi-vxflexos/Chart.yaml
- charts/csi-vxflexos/values.yaml
- installation-wizard/container-storage-modules/Chart.yaml
- installation-wizard/container-storage-modules/values.yaml
No
This PR bumps up the csi-vxflexos version 
> `charts/csi-vxflexos` version bump up

- .github/dependabot.yml
No
Update dependabot config to run against authorization v2 chart.
> [charts/csm-authorization-v2.0] Enable dependabot for authorization v2

- .github/dependabot.yml
No
Update dependabot config to run against csi-powerstore chart.
> Add dependabot compatibility for csi-powerstore images

- .github/dependabot.yml
- charts/csi-unity/templates/controller.yaml
- charts/csi-unity/templates/node.yaml
- charts/csi-unity/values.yaml
csi-unity
Tested by running helm template --dependency-update charts/csi-unity and manually inspecting the resulting yaml for proper image specifications.
Is this a new chart?
No
What this PR does / why we need it:
Which issue(s) is this PR associated with:
https://github.com/dell/csm/issues/1414
Special notes for your reviewer:
> Adding dependabot compatibility for csi-unity

- charts/csi-vxflexos/templates/node.yaml
- charts/csi-vxflexos/values.yaml
No
Adds an option to disable installation of the SDC via the init-container.
- https://github.com/dell/csm/issues/663
Tested by installing the CSI PowerFlex driver without the SDC init-container. Confirmed that the SDC was not installed.
> [charts/csi-vxflexos] Add flag to enable or disable the SDC init container

- charts/csi-vxflexos/templates/node.yaml
No
This PR fixes the issue when the sdc.enabled field does not exist in values.yaml. We should default the SDC install to true to remain backwards compatible.
The helm template condition is to install the SDC based on following: `If sdc.enabled field is missing or sdc.enabled=true`
- https://github.com/dell/csm/issues/663
Tested by installing the helm chart with a missing sdc.enabled field and by explicitly setting sdc.enabled to true and then false.
> [charts/csi-vxflexos]: Enable SDC by default if not explicitly set

- charts/csi-unity/Chart.yaml
- charts/csi-unity/values.yaml
- installation-wizard/container-storage-modules/Chart.yaml
- installation-wizard/container-storage-modules/values.yaml
Yes
- https://github.com/dell/csm/issues/1478
> Add helm charts for Unity v2.11.1

- .github/dependabot.yml
No
csm-replication
Tested by running helm template --dependency-update charts/csm-replication and manually inspecting the resulting yaml for proper image specifications.
Note: The values.yaml file didn't need updating because it already used image as the value name
> [charts/csm-replication] Adding dependabot compatibility for csm-replication images

- charts/csi-powerstore/Chart.yaml
- charts/csi-powerstore/values.yaml
- charts/csi-unity/Chart.yaml
- charts/csi-unity/values.yaml
- installation-wizard/container-storage-modules/Chart.yaml
- installation-wizard/container-storage-modules/values.yaml
Yes
- https://github.com/dell/csm/issues/1478
> Release v1.11.1

- .github/dependabot.yml
No
Update dependabot config to run against csi-powermax chart.
> [charts/csi-powermax]: Add dependabot compatibility for csi-powermax images

- charts/csi-vxflexos/templates/controller.yaml
- charts/csi-vxflexos/templates/driver-config-params.yaml
- charts/csi-vxflexos/templates/node.yaml
- charts/csi-vxflexos/values.yaml
No
- Permissions to perform get and update on the configMap to get the Interface IPs required for disabling the SDC dependency while provisioning NFS Volumes with PowerFlex
- https://github.com/dell/csm/issues/663
> Adding Interfaces for disabling SDC dependency on Powerflex NFS Volumes

- .github/dependabot.yml
No
csm-installer
Tested by inserting mock values in the yaml file for certificates and keys then running helm template --dependency-update charts/csm-installer and manually inspecting the resulting yaml for proper image specifications.
> [charts/csm-installer] Adding dependabot compatibility for csm-installer images

- charts/csi-isilon/templates/csidriver.yaml
- charts/csi-powerstore/templates/csidriver.yaml
- charts/csi-unity/templates/csidriver.yaml
- charts/csi-vxflexos/templates/csidriver.yaml
No
Per https://access.redhat.com/solutions/7076474 and https://docs.openshift.com/container-platform/4.13/storage/container_storage_interface/ephemeral-storage-csi-inline.html#security-profile-enforcement, a label must be set on the CSIDriver for OpenShift to allow the creation of inline ephemeral volumes for cluster versions < 4.17. In 4.17, inline ephemeral volumes can created without the CSIDriver label but there will be a warning.
`W1011 10:12:27.323610  372718 warnings.go:70] pod-ephemeral-test-964kf uses an inline volume provided by CSIDriver csi-isilon.dellemc.com and namespace functional-test has a pod security warn level that is lower than privileged
`
- Adds the `security.openshift.io/csi-ephemeral-volume-profile: restricted` label to the CSIDriver resources that support …
> [bug-1502]: Add csi-ephemeral-volume-profile label to CSIDriver

- .github/dependabot.yml
- installation-wizard/container-storage-modules/values.yaml
installation-wizard/container-storage-modules
Tested by generating the `values.yaml` file from the update format through `csm-docs/installation-wizard` and installing that with updated Charts pointing to the local charts for each dependency.
Note: The values.yaml file didn't need updating because it already used image as the value name
No
> [installation-wizard/container-storage-modules] Adding dependabot compatibility for installation-wizard charts

- charts/csi-isilon/Chart.yaml
- charts/csi-isilon/values.yaml
- charts/csi-powermax/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/values.yaml
- charts/csi-powermax/values.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-powerstore/values.yaml
- installation-wizard/container-storage-modules/Chart.yaml
- installation-wizard/container-storage-modules/values.yaml
> Driver version bump for csi-powerstore, csi-powermax and csi-powerscale

- charts/csi-vxflexos/templates/node.yaml
No
This PR addresses the problem documented in issue 1546.
- https://github.com/dell/csm/issues/1546
> [charts/vxflexos] Fix privTgt mount is lost after vxflexos-node pod restart

- charts/csi-powermax/templates/powermax-array-config.yaml
- charts/csi-powermax/values.yaml
No
This PR removes the duplicate entry of powermax endpoint and then powermax-array-config refers to endpoint from storageArrays section.
- https://github.com/dell/csm/issues/1570
Tests performed
- Validated Powermax Driver installation via helm-charts
- Ran certify suit
> powermax endpoint update

- charts/csi-powermax/templates/node.yaml
No
Removes the duplicate mount which is not cleaned up on driver uninstall or pod restart. The issue is described in https://github.com/dell/csm/issues/1659.
- #[1659](https://github.com/dell/csm/issues/1659)
- Ran multiple installation and uninstallation and validated that the problem mount is not there after install and uninstall.
- Ran cert-csi provisioning and volumeio tests to validate operation of the driver.
- Install resiliency which could have been impacted by the changes and Reiliency operation was not impacted.
> [csi-powermax/node] Remove redundant volume mount from the pmax driver container

- charts/csm-authorization-v2.0/values.yaml
- charts/csm-authorization/values.yaml
No
OPA 1.0.0 fails to parse Authorization policies, so we will use the previous version which works.
https://github.com/dell/csm/issues/1661
> [bug-1661]: Use OPA 0.70.0

- charts/csm-authorization-v2.0/templates/proxy-server.yaml
- charts/csm-authorization/templates/proxy-server.yaml
No
ClusterRole "view" already exists on K8s 1.31 cluster. This changes the name of the ClusterRole to not conflict with the existing resource.
- https://github.com/dell/csm/issues/1662
> [csm-authorization] Update ClusterRole view name

- charts/csi-powermax/charts/csireverseproxy/templates/certificate.yaml
- charts/csi-powermax/templates/controller.yaml
- charts/csi-powermax/templates/node.yaml
Yes/No
Update CSI-PowerMax to mount the reverse proxy TLS secret within the driver container.This PR resolves the `cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs` error when `skipCertificateValidation` is set to `false`.
- dell/csm#1571
> Update CSI-PowerMax to mount reverse proxy TLS secret within driver container

- charts/csi-vxflexos/values.yaml
- installation-wizard/container-storage-modules/values.yaml
No
Images that pointed to dockerhub for the PowerFlex SDC have been updated to point to quay.io instead. 
N/A
> csi-vxflexos: Updated SDC images to quay.io

- charts/csi-isilon/values.yaml
- charts/csi-powermax/values.yaml
- charts/csi-powerstore/values.yaml
- charts/csi-unity/values.yaml
- charts/csi-vxflexos/values.yaml
No
- https://github.com/dell/helm-charts/issues/584
> Release v1.13.0 Rebase

- charts/csi-powermax/charts/csireverseproxy/templates/reverseproxy.yaml
- charts/csi-powermax/templates/controller.yaml
No
These changes mount the existing `powermax-config-params` ConfigMap to the reverse proxy containers (for sidecar and stand-alone deployments) in order to provide global log configuration parameters to the reverse proxy when using the new secret format.
- https://github.com/dell/csm/issues/1614
- Because the log parameters are already captured in the `powermax-config-params` ConfigMap, it will be mounted as a volume to the reverse proxy container. All of the volume configurations for the reverse proxy container match the existing configuration to containers that already utilize this ConfigMap.
Using the latest images for the driver and reverse proxy, compiled from https://github.com/dell/csi-powermax/pull/418:
- **Validation:** Manually deployed with `global.useSecret: true` and checked …
> charts/csi-powermax: Mount ConfigMap with log details to reverse proxy containers

- charts/csi-powermax/charts/csireverseproxy/templates/reverseproxy.yaml
- charts/csi-powermax/templates/controller.yaml
- charts/csi-powermax/templates/driver-config-params.yaml
No
These changes add the reverse proxy port to the existing `powermax-config-params` ConfigMap in order to provide the reverse proxy service port to the driver and proxy containers when using the new secret format.
- https://github.com/dell/csm/issues/1614
- Updated reverse proxy container envs to provide the file path for the `powermax-config-params` ConfigMap.
Using the latest images for the driver and reverse proxy, compiled from https://github.com/dell/csi-powermax/pull/418:
- **Validation:** Manually deployed with `global.useSecret: true` and checked the reverse proxy container directories for the mounted configmap contents in both stand-alone and sidecar reverse proxy modes.
- **Validation:** Manually deployed with `global.useSecret: true` and ran cert-csi volume-io tests for both …
> charts/csi-powermax: Provide reverse proxy port info when using new secret mount.

- charts/karavi-observability/templates/karavi-metrics-powermax.yaml
- charts/karavi-observability/values.yaml
No
The changes mount the `powermax-reverseproxy-secret` to the karavi-metrics container for the Observability module to read the configuration from the secret in case of useSecret is set to true. 
- https://github.com/dell/csm/issues/1614
> charts/karavi-observability: Mount powermax-reverseproxy-secret to karavi container.

- charts/karavi-observability/templates/karavi-metrics-powermax.yaml
No
Update variable name used in observability to the same name used in csi-powermax.
This var determines whether or not to use the new secret format.
https://github.com/dell/csm/issues/1614
> charts/karavi-observability: update useSecret env var name

- charts/csi-vxflexos/templates/node.yaml
No
- Removes the `<KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com/disks` volume mount to not cause duplicate mounts with the `<KUBELET_CONFIG_DIR>/plugins/vxflexos.emc.dell.com` mount
- Removes the `/noderoot` mount so that duplicate mounts are not under `/noderoot`
- Mounts `/bin/emc/scaleio/` and `/opt/emc/scaleio/sdc/bin/` for drv_cfg execution instead of the entire root filesystem
https://github.com/dell/csm/issues/1782
N/A
[cert-csi.log](https://github.com/user-attachments/files/19169783/cert-csi.log)
> [charts/csi-powerflex] Resolve stale and duplicate disk mounts

- charts/csi-vxflexos/templates/node.yaml
No
This PR adds RELEASE_NAME env in driver container for node to facilitate driver configmap update in case of dynamic configmap name used in the driver.
- https://github.com/dell/csm/issues/1774
> [charts/csi-vxflexos] Add RELEASE_NAME env in driver container for node

- charts/csi-vxflexos/templates/node.yaml
Cherry-picked fix for the /noderoot volume issue from PR #674.
Yes/No
> [charts/csi-powerflex] patch for /noderoot volume

- charts/csi-vxflexos/templates/node.yaml
No
Don't mount `/bin/emc/scaleio/` into vxflexos-node for OCP.
https://github.com/dell/csm/issues/1811
> [charts/csi-vxflexos]: Fix SDC mount for OCP

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
- charts/csi-powerstore/values.yaml
No
PR adds flexibility to allow users to specify a port for their NFS traffic for host based NFS volumes (both server and client side ports). It also adds flexibility to allow users to specify export path for host based NFS volumes. If none specified, it defaults to a default value. 
[https://github.com/https://github.com/dell/csm/issues/1742]
> Make NFS exports path and ports configurable

- charts/csi-powermax/templates/controller.yaml
- charts/csi-powermax/templates/node.yaml
- charts/csi-powermax/values.yaml
No
To deprecate powermax-array-config. If in future release we remove powermax-array-config.yaml from helm-charts/charts/csi-powermax/templates , the driver will install using values from values.yaml.
- https://github.com/dell/csm/issues/1776
Tested:
- Installation with this branch and by manually deleting powermax-array-config.yaml from helm-charts/charts/csi-powermax/templates folder
- Upgrade with this branch and by manually deleting powermax-array-config.yaml from helm-charts/charts/csi-powermax/templates folder
- Same scenarios with mount creds also.
> CSI-Powermax: deprecate_array_configmap

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
- charts/csi-powerstore/values.yaml
No
Add HBNFS support for PowerStore. This introduces the necessary RBAC for PowerStore which are needed for HBNFS. Also, it makes it so that all NFS parameters are configurable based on the desired setup.
https://github.com/dell/csm/issues/1742
> [charts/csi-powerstore] Adding Host Based NFS for Powerstore

- charts/csi-unity/templates/controller.yaml
- charts/csi-unity/templates/node.yaml
Reverts dell/helm-charts#681
Even though these changes work well for the driver, they might not be reliable when modules are enabled. We'll keep these updates in a feature branch for now and merge them into the main branch once we've completed the RBAC updates for all components.
> Revert "[charts/csi-unity]: Updating RBAC rules in csi-unity "

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
Reverts dell/helm-charts#684
Even though these changes work well for the driver, they might not be reliable when modules are enabled. We'll keep these updates in a feature branch for now and merge them into the main branch once we've completed the RBAC updates for all components.
> Revert "[charts/csi-powerstore]: Updating RBAC rules in csi-powerstore"

- charts/csi-powermax/templates/node.yaml
Added the Bidirectional mount propagation for the mounted path /var/lib/kubelet/plugins/powermax.emc.dell.com to make the private target path visible to the driver even after its restart.
List the GitHub issues impacted by this PR:
| https://github.com/dell/csm/issues/1843 |
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
> Add Bidirectional mount propagation for powermax driver private target path

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
No
PR to pass the Namespace name as environment variable for Powerstore required for HBNFS
- [https://github.com/dell/csm/issues/1742]
> [charts/csi-powerstore]: Passing the namespace name as Environment variable

- charts/csm-replication/templates/controller.yaml
- charts/csm-replication/values.yaml
No
It provides end user a configurable param which can be set to enable PVC creation on target cluster.
param added -> **allowPvcCreationOnTarget**
- https://github.com/dell/csm/issues/1862
> pvc on target param

- charts/csi-powermax/templates/node.yaml
No
- Moves podmon container in the beginning for the Powermax node to make it consistent with other drivers.
- This changes fixes Resiliency E2E tests for PowerMax for the scenario "Driver Pods Down" where it was patching the driver node pod image with incorrect image.
- https://github.com/dell/csm/issues/1870
Logs: [pmax-resiliency-driver-pods-down.txt](https://github.com/user-attachments/files/19974611/pmax-resiliency-driver-pods-down.txt)
> [charts/csi-powermax]: Adjust podmon container placement in Powermax node 

- charts/csi-powermax/templates/controller.yaml
No
This PR adds watch permission to secrets required by the reverseproxy.
```
Name:         powermax-controller
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: powermax
meta.helm.sh/release-namespace: powermax
PolicyRule:
Resources                   Non-Resource URLs  Resource Names  Verbs
---------                   -----------------  --------------  -----
secrets                     []                 []              [get list]
leases.coordination.k8s.io  []                 []              [get watch list delete update create]
replicasets.apps            []                 []              [get]
pods                        []                 []              [update patch]
[root@master-1-E4hZ2l1eQqy9q dell-csi-helm-installer]# …
```
> [charts/csi-powermax]: Add watch permission to secrets

- charts/csi-isilon/templates/controller.yaml
No
Added new env variable X_CSI_VOL_PREFIX 
- [#Issue_Number](https://github.com/dell/csm/issues/1487)
Associated PRs :
https://github.com/dell/csi-powerscale/pull/383
https://github.com/dell/csm-operator/pull/974
https://github.com/dell/csm-docs/pull/1521
> [charts/csi-powerscale]: Added csi-vol prefix variable

- charts/csm-authorization-v2.0/values.yaml
No
Update storage array poll interval default to 10m.
https://github.com/dell/csm/issues/1707
> [charts/csm-authorization-v2]: Update Authorization storage sample poll Interval 

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/values.yaml
- installation-wizard/container-storage-modules/values.yaml
No
This PR adds following 2 environment variables for configuring multi-NAS in powerstore.
- `X_CSI_MULTI_NAS_FAILURE_THRESHOLD`: Number of consecutive FS creation failures after which a NAS is put into cooldown.
- `X_CSI_MULTI_NAS_COOLDOWN_PERIOD`: Duration for which a NAS remains in cooldown once the threshold is reached.
- https://github.com/dell/csm/issues/1758
> [charts/csi-powerstore] Add Environment Variables for Configuring Multi-NAS in PowerStore 

- charts/csi-powerstore/templates/node.yaml
- charts/csi-powerstore/values.yaml
No
References to variables etc used for shared NFS have been removed. 
Remove references to shared NFS
Testing done:  Re-deployed with these changes, verified cert-csi tests for iscsi are successful. 
TEST RESULTS:
`[2025-05-20 14:50:32]  INFO Starting cert-csi; ver. 1.8.0
[2025-05-20 14:50:32]  INFO Created test_runs table
[2025-05-20 14:50:32]  INFO Created test_cases table
[2025-05-20 14:50:32]  INFO Created events table
[2025-05-20 14:50:32]  INFO Created entities table
[2025-05-20 14:50:32]  INFO Created number_entities table
[2025-05-20 14:50:32]  INFO Created resource_usage table
[2025-05-20 14:50:32]  INFO Created entities_relations table
[2025-05-20 14:50:32]  INFO Created …
> Patch helm charts to remove references for shared nfs

- charts/csi-powermax/templates/controller.yaml
No
Fixed sidecar's timeout across helm and operator for each platform and made them consistent and unified between installation methods.
https://github.com/dell/csm/issues/1905
The changes have been validated for powermax driver 
> Fixed sidecar's timeout across helm and operator for each platform

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
- charts/csi-powerstore/values.yaml
No
This PR adds support for the skipCertificateValidation parameter in the PowerStore CSI driver.
- https://github.com/dell/csm/issues/1911
Tests:
> skipCertificateValidation Support in PowerStore CSI Driver

- charts/csm-authorization-v2.0/templates/storage-service.yaml
No
Added ReadOnly for Volume Mount. Refer to:
- https://github.com/dell/helm-charts/pull/760
- https://github.com/dell/csm/issues/1468
> [charts/csm-authorization-v2.0]: Add ReadOnly for Volume Mount

- charts/csi-powermax/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/Chart.yaml
- charts/csi-powermax/charts/csireverseproxy/values.yaml
- charts/csi-powermax/values.yaml
- charts/csi-powerstore/Chart.yaml
- charts/csi-powerstore/values.yaml
- installation-wizard/container-storage-modules/Chart.yaml
- installation-wizard/container-storage-modules/values.yaml
No
This PR updates the chart for patch version 1.14.1
- dell/csm#1942
> Patch version [1.14.1] update

- charts/csi-vxflexos/Chart.yaml
- charts/csi-vxflexos/templates/controller.yaml
- charts/csi-vxflexos/templates/node.yaml
- charts/csi-vxflexos/values.yaml
No
In an attempt to align with the PowerFlex array default timeout of 10 seconds, we are adding the ability to make this parameter configurable through charts such that the customer has that flexibility during the Probe workflow in the PowerFlex driver. Originally, this parameter defaulted to 1 seconds which caused issues during boot when an array took time to respond to probes. Increasing the default and making it configurable adds an extra level of customizability for the array. 
- https://github.com/dell/csm/issues/1956
> [charts/csi-vxflexos] Add probe timeout to PowerFlex controller and node

- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
No
This introduces a new environment variable which sets volume prefix. This is needed to trim the volume name when using Authorization module.
https://github.com/dell/csm/issues/1947
Reference PR: https://github.com/dell/csi-powerstore/pull/529 having all the test results
> [charts/csi-powerstore] Added env for volume name prefix

- charts/csi-vxflexos/values.yaml
No
This PR adds comment to allow restriction for SDC access for ApprovedIp (GUID and IP address).
- https://github.com/dell/csm/issues/1962
> Update values.yaml for PowerFlex 

- charts/csi-vxflexos/templates/_helpers.tpl
- charts/csi-vxflexos/templates/controller.yaml
No
When using CSM Authorization and CSM Replication together with PowerFlex, the generated volume names can exceed the platform's maximum allowed length of 31 characters. This leads to truncation of the volume name, which reduces its uniqueness and may result in naming conflicts or duplicate volume names.
This PR adds a precheck during the driver deployment to ensure the volume name prefix length < 5 chars with Authorization and Replication module enabled.
(https://github.com/dell/csm/issues/1992)
None
> [charts/csi-vxflexos] Add a precheck to check volume name prefix length with Authorization and Replication modules enabled.

- charts/csm-authorization-v2.0/charts/redis/templates/redis.yaml
- charts/csm-authorization-v2.0/charts/redis/templates/sentinel.yaml
- charts/csm-authorization-v2.0/charts/redis/values.yaml
- charts/csm-authorization-v2.0/templates/proxy-server.yaml
- charts/csm-authorization-v2.0/templates/storage-service.yaml
- charts/csm-authorization-v2.0/templates/tenant-service.yaml
- charts/csm-authorization-v2.0/values.yaml
No
https://github.com/dell/csm/issues/1468
Installed Authorization V2 successfully and created Auth resources including storage, role, and tenant, which became all ready and available in the follow scenarios:
> [charts/csm-authorization-v2.0]: Add Conjur support for Redis secret to CSM Authorization

- charts/csm-authorization-v2.0/charts/redis/values.yaml
- charts/csm-authorization-v2.0/templates/proxy-server.yaml
- charts/csm-authorization-v2.0/templates/storage-service.yaml
- charts/csm-authorization-v2.0/templates/tenant-service.yaml
- charts/csm-authorization-v2.0/values.yaml
No
- Supports [karavi config secret](https://dell.github.io/csm-docs/docs/getting-started/installation/kubernetes/powerflex/helm/csm-modules/authorizationv2-0/#install-container-storage-modules-authorization) coming from a SecretProviderClass object. 
- Both Vault and Conjur
- Ensures a SPC is only mounted a single time even if it used for multiple secrets, ex: redis and storage
https://github.com/dell/csm/issues/1468
Tests:
Installed Authorization V2 successfully and created Auth resources including storage, role, and tenant, which became all ready and available in the follow scenarios:
- storage creds and config secret shared the same SPC
- redis and config secret shared the same SPC
- redis and …
> [charts/csm-authorization-v2.0]: Add SecretProviderClass (Vault/Conjur) support for karavi config secret to CSM Authorization

- charts/csi-isilon/templates/controller.yaml
- charts/csi-isilon/templates/node.yaml
- charts/csi-isilon/values.yaml
- charts/csi-powermax/templates/controller.yaml
- charts/csi-powermax/templates/node.yaml
- charts/csi-powerstore/templates/controller.yaml
- charts/csi-powerstore/templates/node.yaml
- charts/csi-vxflexos/templates/controller.yaml
- charts/csi-vxflexos/templates/node.yaml
- charts/csm-authorization-v2.0/charts/redis/templates/sentinel.yaml
No
This PR removes the dependency on the _karavi-authorization-config_ secret for deploying Auth v2 with PowerStore, PowerFlex, PowerScale, and PowerMax. With this change, new deployments only require the driver secret, simplifying the configuration process.
The existing deployments using the _karavi-authorization-config_ secret will continue to function as expected, ensuring seamless upgrades.
- https://github.com/dell/csm/issues/1583
Testing:
Logs are attached to the internal stories.
- Greenfield - Auth e2e: 
- using _karavi-authorization-config_ secret
- using driver secret
- Upgrade - Auth e2e: 
- continue to use _karavi-authorization-config_ secret
- switch over to driver secret. i.e delete …
> Simplify Auth v2 deployment by removing karavi-authorization-config Secret requirement
